sudo: false

matrix:
  include:
    - language: python
      python: "2.7"
      env: TOXENV=py27

    - language: python
      python: "3.5"
      env: TOXENV=py35

    - language: python
      python: "3.6"
      env: TOXENV=py36

addons:
  apt:
    packages:
      - lcov

install:
  - pip install -U pip wheel codecov
  - make test_requirements

script:
  - tox

after_success:
  - codecov

deploy:
  provider: pypi
  user: edx
  password:
    secure: vIuWvQ5MgvA4fWAugRTTDbRqFQlKwtt2VEVK6XJNPDwtqq956TJ1qll6jtECv90hBO/dXpbj+151P2fgWD5d6OuHagD4lXaZ9sBziClBXbaowjeGH6xG3xScvo7+oJ+2vVh/xNk4Pqv2YdbOBTbP79vRW/3rrfFnjPpd4K2Ipvs=
  distributions: sdist bdist_wheel
  on:
    tags: true
